<a href="https://colab.research.google.com/github/Echester97/Machine_learning/blob/Main-branch/Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

** PROBLEM 1** Matrix product is calculated manually

# Matrix Product of A and B

We are given the following matrices:


A =
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{bmatrix}



B =
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{bmatrix}


The element c<sub>ij</sub> of the product matrix  C = A*B is computed as:
\begin{equation}
c_{ij} = \sum_{k=1}^{3} a_{ik} \cdot b_{kj}
\end{equation}
---

## Cálculo Paso a Paso

### 1. Fila 1 de \(C\):
- **c<sub>11</sub>:**

  \begin{equation}
  c_{11} = (-1) \times 0 + 2 \times 0 + 3 \times 2 = 0 + 0 + 6 = 6
  \end{equation}

- **c<sub>12</sub>:**

  \begin{equation}
  c_{12} = (-1) \times 2 + 2 \times 2 + 3 \times 9 = -2 + 4 + 27 = 29
  \end{equation}

- **c<sub>13</sub>:**

  \begin{equation}
  c_{13} = (-1) \times 1 + 2 \times (-8) + 3 \times (-1) = -1 - 16 - 3 = -20
  \end{equation}

---

### 2. Fila 2 de \(C\):

- **c<sub>21</sub>:**

  \begin{equation}
  c_{21} = 4 \times 0 + (-5) \times 0 + 6 \times 2 = 0 + 0 + 12 = 12
  \end{equation}

- ***c<sub>22</sub>:**

  \begin{equation}
  c_{22} = 4 \times 2 + (-5) \times 2 + 6 \times 9 = 8 - 10 + 54 = 52
  \end{equation}

- **c<sub>23</sub>:**

  \begin{equation}
  c_{23} = 4 \times 1 + (-5) \times (-8) + 6 \times (-1) = 4 + 40 - 6 = 38
  \end{equation}

---

### 3. Fila 3 de \(C\):

- **c<sub>31</sub>:**

  \begin{equation}
  c_{31} = 7 \times 0 + 8 \times 0 + (-9) \times 2 = 0 + 0 - 18 = -18
  \end{equation}

- **c<sub>32</sub>:**

  \begin{equation}
  c_{32} = 7 \times 2 + 8 \times 2 + (-9) \times 9 = 14 + 16 - 81 = -51
  \end{equation}

  **c<sub>33</sub>:**

  \begin{equation}
  c_{33} = 7 \times 1 + 8 \times (-8) + (-9) \times (-1) = 7 - 64 + 9 = -48
  \end{equation}

---
## Matriz Producto Resultante

La matriz C es:


C =
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 \\
\end{bmatrix}


---


**PROBLEM 2** Calculation by NumPy function

In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


**PROBLEM 3** Implementation of calculation of a certain element

In [7]:
result = 0
for k in range(a_ndarray.shape[1]):
  result += a_ndarray[0, k] * b_ndarray[k, 0]
print(f"C[0,0]= {result}")



C[0,0]= 6


**PROBLEM 4, 5** Creating a function that performs matrix multiplication

In [12]:
def matrix_multiplication(a, b):
    m, n = a.shape
    n2, p = b.shape
    if n != n2:
        raise ValueError("Number of columns in A must match the number of rows in B")

    C = np.zeros((m, p))

    for i in range(m):
      for j in range(p):
        for k in range(n):
            C[i, j] += a[i, k] * b[k, j]

    return C


a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print('Matrix A (Input):')
print(a_ndarray)
print('\nMatrix B (Input):')
print(b_ndarray)

C = matrix_multiplication(a_ndarray, b_ndarray)
print('\nMatrix C (Output):')
print(C)



Matrix A (Input):
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Matrix B (Input):
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]

Matrix C (Output):
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


**PROBLEM 6** Transposition

In [13]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
e_transpose  = np.transpose(e_ndarray)
result = matrix_multiplication(d_ndarray, e_transpose)
print(result)

[[ 46.  -4.]
 [-34.  73.]]
